### ISSUE TITLE
Arduino nano 33 ble compatibility with a NINA W10 co-processor?

### ISSUE THREAD

**Issue by Colas-Lepoutre** [khoih-prog/WiFiNINA_Generic#3]
Hi,
I'm currently trying to make the Adafruit ItsyBitsy Esp32 co-processor add-on work with the arduino Nano 33 BLE. 

I tried using the Adafruit WifiNINA and the WifiNINA_generic libraries. At first the examples weren't compiling, however, by adding the "arduino::" prefix to each call of the IPAddress, UDP and Print classes in the WifiUdp.h file, I managed to make it compile. 
This being done, I thought it would work but no, I get the message "Communication with WiFi module failed!". I checked my wiring a hundred times, nothing changes.
I tried making it work with the MKR 1310 board (SAMD21 processor) and I succeded.

I guess that what's causing trouble is the fact that the Nano 33 BLE is based on MBED OS and is not fully supporting every arduino features. However, I was wondering if someone had any infos on how to make it work.

Thanks in advance,
Colas LEPOUTRE

**Comment by khoih-prog** [comment]
I suggest you don't use Nano 33 BLE for WiFi/Ethernet as the **basic support is still lacking.** I'm afraid this is a main reason not many people can use Nano 33 BLE for something useful. Just run an example of **TensorFlowLite**, then get bored, and leave the board forgotten.

IMHO, In order to start developing using Nano 33 BLE on Arduino IDE with Mbed, we have to fix the Mbed support package first (too many works to do)

Then start writing / porting many low level libraries to provide basic support, for example
- TCP/IP, lwIP
- LittleFS
- Many more missing necessary supporting libraries

The ideal way is to upload the BootLoader using Adafruit's nRF52840-based board BootLoader to get away from Mbed, then use Adafruit board packages for all your development.

I was planning to do this, but had to drop that in the middle as the BootLoader reprogramming support is still terrible. I'll definitely go back to finish in the near future ;-(

If you have to do it urgently, I suggest you use Adafruit nRF52840 board, such as Feather nRF52840 Express, Itsy-Bitsy nRF52840 Express to avoid the headache. WiFi/WiFiNINA/Ethernet are already supporting the Adafruit boards. The extra sensors are easily added by using a small add-on board.

Good Luck.
